apiVersion: v1
kind: PersistentVolume
metadata:
  name: caddy-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual2
  hostPath:
    path: "/mnt/data"

